name: gh-pages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build static site
        run: |
          mkdir -p docs/
          for name in *.link; do
            if [ ! -f "$name" ]; then
              continue
            fi
            url="$(cat "$name")"
            dir=docs/$name/
            mkdir -p "$dir"
            cat <<HTML > "$dir/index.html"
          <!DOCTYPE html>
          <html>
            <head>
              <title>Redirecting...</title>
              <meta http-equiv="refresh" content="0; URL='$url'" />
            </head>
            <body>Redirecting to <a href="$url">$url</a></body>
          </html>
          HTML
          done
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add docs
          git diff --cached --exit-code || git commit -m "Rebuild site"
          git push origin master
